### ISSUE TITLE
OptionalRules import error

### ISSUE THREAD

**Issue by ting830812** [MahjongRepository/mahjong#12]
Hi, 

Just let you know that when I use `pip install mahjong`, I will get version 1.1.6 which is not including `OptionalRules` in `mahjong.hand_calculating.hand_config`. 
Therefore, the example code of open set in `readme.rst` cannot be executed with `options=OptionalRules(has_open_tanyao=True)`.

Thanks

**Comment by Nihisil** [comment]
Thank you for the report! I have released `1.1.7` with `OptionalRules` class.
