### ISSUE TITLE
Suggestions of new features

### ISSUE THREAD

**Issue by profthecopyright** [MahjongRepository/mahjong#25]
I just found this repo. Wonderful!

1. Should we include honba （本場）numbers into HandConfig for adjustment of cost calculations?
2. Should we include the tiles that lead to less shanten number in the return value of the shanten calculator so that it would be the same as in [url]https://tenhou.net/2/

**Comment by Nihisil** [comment]
Thanks for the suggestions. I don't mind if these features will be added to the lib code.

**Comment by profthecopyright** [comment]
OK thanks I will take care of this. And also, could I add a Chinese version of the docs and the yaku names so that Chinese majhong players (and programmers) can use this library more easily?

**Comment by Nihisil** [comment]
Sure! Thanks. Maybe while you are here you integrate some localization system, so we will have separate localization files for yaku names instead of `name_en`, `name_jp` attributes.

**Comment by Nihisil** [comment]
Thank you! It could be default python lib https://docs.python.org/3/library/gettext.html

Also, If you feel that you don't want to do it, it is ok to simply add new attr with Chinise version.

**Comment by profthecopyright** [comment]
OK I can try to do the locale system in the next version.

**Comment by Enerccio** [comment]
If you are adding honba, don't forget basengo (5x increase) as optional rule too

**Comment by profthecopyright** [comment]
> basengo

Good reminder. I am currently working on an optional rule supporting system, as there would be a lot more optional rules to include such as syuugi, etc.
