### ISSUE TITLE
Sanshoku Douko fails if one set is a kan

### ISSUE THREAD

**Issue by joeygannon** [MahjongRepository/mahjong#39]
This check fails if one of the sets is a kan, because the lists are different lengths. It may be preferable to just compare the first element of each set.
https://github.com/MahjongRepository/mahjong/blob/416b5d914ca69354d3793eb800bc1944153ff9f8/mahjong/hand_calculating/yaku_list/sanshoku_douko.py#L47

**Comment by Nihisil** [comment]
Thanks for the bug report.
